spring:
  cloud:
    gateway:
      routes:
      - id: svc1_route
        uri: http://localhost:8081/**
        predicates:
          - Path=/svc1/**
        filters:
          - StripPrefix=1
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG